spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yana_db
    username: postgres
    password: momen

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

---

springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
